---
- name: "Static Website Installation"
  become: yes
  hosts: "{{ env }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create network
      community.docker.docker_network:
        name: django 

    - name: Create default containers
      community.docker.docker_container:
        name: "postgres"
        image: "docker.io/postgres:14.2-alpine"
        state: started
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        networks: 
          - name: django
        restart: "yes"

    - name: Create default containers
      community.docker.docker_container:
        name: "django"
        image: "docker.io/matt2022dockertp/django:nightly"
        state: started
        env:
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        networks: 
          - name: django
        restart: "yes"
        ports: "8000:8000"
...
